changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - '*'
